import { MigrationInterface, QueryRunner } from "typeorm";

export class FirstMigration1781666376466 implements MigrationInterface {
    name = 'FirstMigration1781666376466'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "matiere" ("id" SERIAL NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "coefficient" numeric(5,2) NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_515728844635ba7121f7a029e03" UNIQUE ("code"), CONSTRAINT "PK_dc64751218014af8d3ef885facb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "niveau" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6d83eba95a8ba1992c674c47f48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "classe" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f5164b0fb85545cd6d8e86b6b70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "etablissement" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "address" character varying(50) NOT NULL, "email" character varying NOT NULL, "phone" character varying(20), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ade77835cea2d763cc5fa65b6fa" UNIQUE ("email"), CONSTRAINT "PK_91b0f5827bfb5ec6c2fbe57af04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "affectation" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "enseignantId" integer, "matiereId" integer, "etablissementId" integer, "niveauId" integer, CONSTRAINT "PK_dd9c6af8306b9c2d9da3eebf555" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "parent" ("id" SERIAL NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "gender" character varying NOT NULL, "email" character varying, "phoneNumber" character varying NOT NULL, "address" character varying, "job" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bf93c41ee1ae1649869ebd05617" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sanction" ("id" SERIAL NOT NULL, "type" character varying NOT NULL DEFAULT 'Avertissement', "motif" text NOT NULL, "dateDecision" date NOT NULL, "dateDebut" date, "dateFin" date, "isApplied" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "etudiantId" integer NOT NULL, CONSTRAINT "PK_8e0d7d8cef573a237bb11a61c8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "note" ("id" SERIAL NOT NULL, "value" numeric(4,2) NOT NULL, "remark" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "etudiantId" integer NOT NULL, "evaluationId" integer NOT NULL, CONSTRAINT "UQ_6b12ae8d81efb7f2ab381d5bef6" UNIQUE ("etudiantId", "evaluationId"), CONSTRAINT "PK_96d0c172a4fba276b1bbed43058" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "evaluation" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'Contrôle Continu', "session" character varying NOT NULL DEFAULT 'Normale', "weight" numeric(5,2) NOT NULL DEFAULT '1', "date" date NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "matiereId" integer NOT NULL, "classeId" integer NOT NULL, "niveauId" integer NOT NULL, "semestreId" integer NOT NULL, CONSTRAINT "PK_b72edd439b9db736f55b584fa54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "semestre" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "anneeUniversitaireId" integer NOT NULL, CONSTRAINT "PK_1e3b225e8f25f6f8d91009afb70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "annee_universitaire" ("id" SERIAL NOT NULL, "label" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isActive" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9003ace7452251b255f7ae1ce02" UNIQUE ("label"), CONSTRAINT "PK_6ea90bd4eeea414bba6ffbd936b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inscription" ("id" SERIAL NOT NULL, "dateInscription" date NOT NULL DEFAULT ('now'::text)::date, "status" character varying NOT NULL DEFAULT 'Actif', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "etudiantId" integer NOT NULL, "anneeUniversitaireId" integer NOT NULL, "classeId" integer NOT NULL, "niveauId" integer NOT NULL, "etablissementId" integer NOT NULL, CONSTRAINT "UQ_c6005fe9cb239efcf5ad87e1f19" UNIQUE ("etudiantId", "anneeUniversitaireId"), CONSTRAINT "PK_e3ec336b4b1fd26e2370893d24b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "etudiant" ("id" SERIAL NOT NULL, "matricule" character varying, "lastName" character varying NOT NULL, "firstName" character varying NOT NULL, "birthDate" date, "birthPlace" character varying, "gender" character varying, "email" character varying NOT NULL, "phoneNumber" character varying, "address" text, "nationality" character varying, "photoPath" character varying, "cin" character varying, "cinDeliveryDate" date, "cinDeliveryPlace" character varying, "baccDiploma" boolean NOT NULL DEFAULT false, "residenceCertificate" boolean NOT NULL DEFAULT false, "birthCertificate" boolean NOT NULL DEFAULT false, "cinCopy" boolean NOT NULL DEFAULT false, "identityPhoto" boolean NOT NULL DEFAULT false, "transfertFile" boolean NOT NULL DEFAULT false, "cartonChemise" boolean NOT NULL DEFAULT false, "enveloppe" boolean NOT NULL DEFAULT false, "gant" boolean NOT NULL DEFAULT false, "alcohol" boolean NOT NULL DEFAULT false, "status" character varying NOT NULL DEFAULT 'Actif', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "etablissementId" integer NOT NULL, "classeId" integer NOT NULL, "niveauId" integer NOT NULL, CONSTRAINT "UQ_dc8b137ca31f803fb6cd251fbe3" UNIQUE ("matricule"), CONSTRAINT "UQ_38adaa770bbec9142fd6f5bd055" UNIQUE ("email"), CONSTRAINT "PK_a841dd0ece1ea4dcc85e8be9e57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('SuperAdmin', 'Admin', 'Enseignant', 'Etudiant', 'Parent', 'Comptable', 'Surveillant')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "password" character varying, "role" "public"."user_role_enum" NOT NULL DEFAULT 'Etudiant', "isActive" boolean NOT NULL DEFAULT true, "etablissementId" integer, "resetPasswordToken" character varying, "resetPasswordExpires" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "enseignantId" integer, "etudiantId" integer, "parentId" integer, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "REL_b9c580c0212198ddb97e5ea5bd" UNIQUE ("enseignantId"), CONSTRAINT "REL_f79fcd085b54535dac75c3067b" UNIQUE ("etudiantId"), CONSTRAINT "REL_c86f56da7bb30c073e3cbed4e5" UNIQUE ("parentId"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "enseignant" ("id" SERIAL NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying, "matricule" character varying NOT NULL, "photoPath" character varying, "dateEmbauche" date NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_86e908b680cdb6da7df18e81ea6" UNIQUE ("email"), CONSTRAINT "UQ_5dde253dba03d3f43421f4d8fad" UNIQUE ("matricule"), CONSTRAINT "PK_3398c38d2795f7d038a86472e5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "salle" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "location" character varying, "capacity" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "etablissementId" integer NOT NULL, CONSTRAINT "PK_e85e090433d93f866a116d0c5b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "emploi_du_temp" ("id" SERIAL NOT NULL, "startTime" TIMESTAMP NOT NULL, "endTime" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "matiereId" integer, "enseignantId" integer, "etablissementId" integer, "classeId" integer, "niveauId" integer, "salleId" integer, CONSTRAINT "PK_aab07ec8e95571027c036fdbb73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "presence" ("id" SERIAL NOT NULL, "status" character varying NOT NULL DEFAULT 'Présent', "remark" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "etudiantId" integer NOT NULL, "emploiDuTempId" integer NOT NULL, CONSTRAINT "UQ_f96111f32ff31eede80d5c3afd8" UNIQUE ("etudiantId", "emploiDuTempId"), CONSTRAINT "PK_e0088b38d7cf2dc6ad815d33e7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "daily_report" ("id" SERIAL NOT NULL, "date" date NOT NULL, "observations" text, "supervisorName" character varying NOT NULL, "totalAbsences" integer NOT NULL DEFAULT '0', "totalRetards" integer NOT NULL DEFAULT '0', "totalSanctions" integer NOT NULL DEFAULT '0', "isSubmitted" boolean NOT NULL DEFAULT false, "pdfUrl" character varying, "etablissementId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6f51b9eb292151755dc3ade12b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c5111c7228266231d9a0b584cd" ON "daily_report"  ("date", "etablissementId") `);
        await queryRunner.query(`CREATE TABLE "generated_document" ("id" SERIAL NOT NULL, "type" character varying NOT NULL, "filePath" character varying NOT NULL, "etudiantId" integer NOT NULL, "generatedById" integer, "etablissementId" integer NOT NULL, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2e0eecfa4a027e77bdc425dac63" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text, "category" character varying NOT NULL DEFAULT 'Autre', "filePath" character varying NOT NULL, "originalName" character varying, "mimeType" character varying, "fileSize" bigint, "etablissementId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e57d3357f83f3cdc0acffc3d777" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "frais" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "type" character varying NOT NULL DEFAULT 'Scolarité', "etablissementId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "classeId" integer, "niveauId" integer, CONSTRAINT "PK_55e3a9ebf62fb0f7bc78268b0ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "paiement" ("id" SERIAL NOT NULL, "reference" character varying NOT NULL, "montant" numeric(12,2) NOT NULL, "datePaiement" date NOT NULL, "modePaiement" character varying NOT NULL DEFAULT 'Espèces', "recuPath" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "etudiantId" integer NOT NULL, "factureId" integer, CONSTRAINT "UQ_d8f7e3de0c57b3553585ddff3e4" UNIQUE ("reference"), CONSTRAINT "PK_decd14b2547ef2439fe89652b06" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "facture" ("id" SERIAL NOT NULL, "numero" character varying NOT NULL, "dateEmission" date NOT NULL, "dateEcheance" date, "montantTotal" numeric(12,2) NOT NULL, "status" character varying NOT NULL DEFAULT 'Brouillon', "notes" text, "quittancePath" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "etudiantId" integer NOT NULL, "anneeUniversitaireId" integer, CONSTRAINT "UQ_6fda9cc1daf5b4bca5b708b3de0" UNIQUE ("numero"), CONSTRAINT "PK_0ad1064da893f894e39f961ca67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."discipline_category_enum" AS ENUM('Règlement Intérieur', 'Discipline', 'Autre')`);
        await queryRunner.query(`CREATE TABLE "discipline" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "category" "public"."discipline_category_enum" NOT NULL DEFAULT 'Discipline', "isActive" boolean NOT NULL DEFAULT true, "etablissementId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_139512aefbb11a5b2fa92696828" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "devoir" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "deadline" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "matiereId" integer NOT NULL, "classeId" integer NOT NULL, "niveauId" integer NOT NULL, "enseignantId" integer NOT NULL, CONSTRAINT "PK_8103c62f0758f86a2e6ba1f5504" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "submission" ("id" SERIAL NOT NULL, "comment" text, "submittedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "devoirId" integer NOT NULL, "etudiantId" integer NOT NULL, "documentId" integer NOT NULL, CONSTRAINT "UQ_ac2c1945b17ea4ee60b9485b0e9" UNIQUE ("devoirId", "etudiantId"), CONSTRAINT "PK_7faa571d0e4a7076e85890c9bd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."global_setting_category_enum" AS ENUM('ACADEMIC', 'FINANCIAL', 'SYSTEM', 'SECURITY')`);
        await queryRunner.query(`CREATE TABLE "global_setting" ("key" character varying NOT NULL, "value" text NOT NULL, "description" text, "category" "public"."global_setting_category_enum" NOT NULL DEFAULT 'SYSTEM', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5d48351912deefef9e2211e771a" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "matiere_classes_classe" ("matiereId" integer NOT NULL, "classeId" integer NOT NULL, CONSTRAINT "PK_623e36093ad299e6956d24945a8" PRIMARY KEY ("matiereId", "classeId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22a30809aa7986c75e2039415c" ON "matiere_classes_classe"  ("matiereId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a2869b0551842a5c9451022ccf" ON "matiere_classes_classe"  ("classeId") `);
        await queryRunner.query(`CREATE TABLE "matiere_niveaux_niveau" ("matiereId" integer NOT NULL, "niveauId" integer NOT NULL, CONSTRAINT "PK_5f4078b669639b225fc0cfe984d" PRIMARY KEY ("matiereId", "niveauId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac166a6307dbb4c3444883bcb0" ON "matiere_niveaux_niveau"  ("matiereId") `);
        await queryRunner.query(`CREATE INDEX "IDX_510ff6dfa7c7fc7db89454b3de" ON "matiere_niveaux_niveau"  ("niveauId") `);
        await queryRunner.query(`CREATE TABLE "classe_niveaux_niveau" ("classeId" integer NOT NULL, "niveauId" integer NOT NULL, CONSTRAINT "PK_8abe631228d79cf98d672a725a0" PRIMARY KEY ("classeId", "niveauId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0751cfed69f5118e28b0f59cc5" ON "classe_niveaux_niveau"  ("classeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b539ebc24d214d2b9d475ccb0" ON "classe_niveaux_niveau"  ("niveauId") `);
        await queryRunner.query(`CREATE TABLE "classe_etablissements_etablissement" ("classeId" integer NOT NULL, "etablissementId" integer NOT NULL, CONSTRAINT "PK_ada4c62026579b17bbc93fa6e35" PRIMARY KEY ("classeId", "etablissementId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_784cc0d337f317933fcb60e8cd" ON "classe_etablissements_etablissement"  ("classeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_088b44971f54346dcfc8d65e65" ON "classe_etablissements_etablissement"  ("etablissementId") `);
        await queryRunner.query(`CREATE TABLE "etudiant_parents_parent" ("etudiantId" integer NOT NULL, "parentId" integer NOT NULL, CONSTRAINT "PK_7ef7fcbec20c4ad3e8dd4e620e0" PRIMARY KEY ("etudiantId", "parentId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2212949f041b51e9feba7d1ef7" ON "etudiant_parents_parent"  ("etudiantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5bc7232bd477fd09dfccd0fa2f" ON "etudiant_parents_parent"  ("parentId") `);
        await queryRunner.query(`CREATE TABLE "devoir_documents_document" ("devoirId" integer NOT NULL, "documentId" integer NOT NULL, CONSTRAINT "PK_94e83b6b8633fd483bbe2ad6af6" PRIMARY KEY ("devoirId", "documentId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_321263efd34b2347abc727a3db" ON "devoir_documents_document"  ("devoirId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e178e1719d8888ce676305b6fb" ON "devoir_documents_document"  ("documentId") `);
        await queryRunner.query(`ALTER TABLE "affectation" ADD CONSTRAINT "FK_65869dbaafbed6bf2a16166f751" FOREIGN KEY ("enseignantId") REFERENCES "enseignant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "affectation" ADD CONSTRAINT "FK_acd89d309a795478b5ad80ea88f" FOREIGN KEY ("matiereId") REFERENCES "matiere"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "affectation" ADD CONSTRAINT "FK_9789642b0225bbabaabb3657729" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "affectation" ADD CONSTRAINT "FK_0cab327cd4501e22d71f34adcda" FOREIGN KEY ("niveauId") REFERENCES "niveau"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sanction" ADD CONSTRAINT "FK_96aa9801da4a8adae770d60a786" FOREIGN KEY ("etudiantId") REFERENCES "etudiant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "note" ADD CONSTRAINT "FK_028dab9170f200af38322b8d784" FOREIGN KEY ("etudiantId") REFERENCES "etudiant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "note" ADD CONSTRAINT "FK_9a6eb74f4efaf1c10d9511b86fd" FOREIGN KEY ("evaluationId") REFERENCES "evaluation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluation" ADD CONSTRAINT "FK_29bf8ae04788e70fece77a39fc0" FOREIGN KEY ("matiereId") REFERENCES "matiere"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluation" ADD CONSTRAINT "FK_00a80169171331f141b6d288332" FOREIGN KEY ("classeId") REFERENCES "classe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluation" ADD CONSTRAINT "FK_a635f6de622e9f36bb4098363b1" FOREIGN KEY ("niveauId") REFERENCES "niveau"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluation" ADD CONSTRAINT "FK_c879e3d03a063bfcc941ef8be10" FOREIGN KEY ("semestreId") REFERENCES "semestre"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "semestre" ADD CONSTRAINT "FK_c06f21c4017f0f6be454c1a853a" FOREIGN KEY ("anneeUniversitaireId") REFERENCES "annee_universitaire"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscription" ADD CONSTRAINT "FK_ca3fe1c599dc9cff1cbaa78cb7e" FOREIGN KEY ("etudiantId") REFERENCES "etudiant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscription" ADD CONSTRAINT "FK_8dd3b031b9bac17fee9a4a49cef" FOREIGN KEY ("anneeUniversitaireId") REFERENCES "annee_universitaire"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscription" ADD CONSTRAINT "FK_97bd35545695c54b5a2c325777d" FOREIGN KEY ("classeId") REFERENCES "classe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscription" ADD CONSTRAINT "FK_3742e0aa85aa466967d70a7f2d2" FOREIGN KEY ("niveauId") REFERENCES "niveau"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inscription" ADD CONSTRAINT "FK_6554e7dddc36d921a306fb6752d" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "etudiant" ADD CONSTRAINT "FK_e3766f31057ed43026791719c74" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "etudiant" ADD CONSTRAINT "FK_06fb9edb6e6692c435662451cd1" FOREIGN KEY ("classeId") REFERENCES "classe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "etudiant" ADD CONSTRAINT "FK_46cf6d4bedfa6cc798b41ff2907" FOREIGN KEY ("niveauId") REFERENCES "niveau"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_cb18d5a151a72a134ae51aa0d87" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_b9c580c0212198ddb97e5ea5bd9" FOREIGN KEY ("enseignantId") REFERENCES "enseignant"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_f79fcd085b54535dac75c3067b1" FOREIGN KEY ("etudiantId") REFERENCES "etudiant"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c86f56da7bb30c073e3cbed4e50" FOREIGN KEY ("parentId") REFERENCES "parent"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salle" ADD CONSTRAINT "FK_108d792fb7c93aa0c6dd4c55954" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" ADD CONSTRAINT "FK_1382506f6fd3d07eb8d61f981a9" FOREIGN KEY ("matiereId") REFERENCES "matiere"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" ADD CONSTRAINT "FK_bb3490f327d918721d50af10e80" FOREIGN KEY ("enseignantId") REFERENCES "enseignant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" ADD CONSTRAINT "FK_3f7d27b0ea32948a1600562e8a1" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" ADD CONSTRAINT "FK_7a966c97def9a503efc93fba589" FOREIGN KEY ("classeId") REFERENCES "classe"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" ADD CONSTRAINT "FK_c51abc62a76489a373300d09987" FOREIGN KEY ("niveauId") REFERENCES "niveau"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" ADD CONSTRAINT "FK_fafd307a2d33552eac0d6c9b813" FOREIGN KEY ("salleId") REFERENCES "salle"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presence" ADD CONSTRAINT "FK_bd046074eae94d956a26d543596" FOREIGN KEY ("etudiantId") REFERENCES "etudiant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "presence" ADD CONSTRAINT "FK_5875ce03aa167454398165438bc" FOREIGN KEY ("emploiDuTempId") REFERENCES "emploi_du_temp"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_report" ADD CONSTRAINT "FK_5ac09ae78730d47cd5ff9709aca" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "generated_document" ADD CONSTRAINT "FK_24429ddfd06252b36dfcad9b64a" FOREIGN KEY ("etudiantId") REFERENCES "etudiant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "generated_document" ADD CONSTRAINT "FK_8a4f6342c1497befc72fcf77209" FOREIGN KEY ("generatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "generated_document" ADD CONSTRAINT "FK_5b8e7fe3afc5db77c8fab3562ea" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document" ADD CONSTRAINT "FK_5bda5f75563f39f9c04adb2c2e0" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "frais" ADD CONSTRAINT "FK_e27c9b14dc1e3cd3b1fac93e1a4" FOREIGN KEY ("classeId") REFERENCES "classe"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "frais" ADD CONSTRAINT "FK_6c2e48ceac45e820d2c81d6ad8c" FOREIGN KEY ("niveauId") REFERENCES "niveau"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "frais" ADD CONSTRAINT "FK_91a9941485422fe1bdf62992360" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paiement" ADD CONSTRAINT "FK_017db846a888e629356ff387b9c" FOREIGN KEY ("etudiantId") REFERENCES "etudiant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paiement" ADD CONSTRAINT "FK_3ee9f6d47d1826661643362f095" FOREIGN KEY ("factureId") REFERENCES "facture"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facture" ADD CONSTRAINT "FK_a570b903e0d06d8224cd9117e11" FOREIGN KEY ("etudiantId") REFERENCES "etudiant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facture" ADD CONSTRAINT "FK_64543711312f99b6b0d20bee443" FOREIGN KEY ("anneeUniversitaireId") REFERENCES "annee_universitaire"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discipline" ADD CONSTRAINT "FK_3715bacd8203d0d4e4b84fba874" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devoir" ADD CONSTRAINT "FK_14a13fbb137c516489e2824e04f" FOREIGN KEY ("matiereId") REFERENCES "matiere"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devoir" ADD CONSTRAINT "FK_dd09647a10e9975c4348b6451c7" FOREIGN KEY ("classeId") REFERENCES "classe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devoir" ADD CONSTRAINT "FK_5491a103593c76073a4c2cd8630" FOREIGN KEY ("niveauId") REFERENCES "niveau"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devoir" ADD CONSTRAINT "FK_b03700a0002517676721f794eb7" FOREIGN KEY ("enseignantId") REFERENCES "enseignant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submission" ADD CONSTRAINT "FK_229a7b4af2a0721748debbe8319" FOREIGN KEY ("devoirId") REFERENCES "devoir"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submission" ADD CONSTRAINT "FK_9c4fbb41ae92b5259998ed4eb02" FOREIGN KEY ("etudiantId") REFERENCES "etudiant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submission" ADD CONSTRAINT "FK_c988039646d519e39bb3e60763b" FOREIGN KEY ("documentId") REFERENCES "document"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matiere_classes_classe" ADD CONSTRAINT "FK_22a30809aa7986c75e2039415cd" FOREIGN KEY ("matiereId") REFERENCES "matiere"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "matiere_classes_classe" ADD CONSTRAINT "FK_a2869b0551842a5c9451022ccf5" FOREIGN KEY ("classeId") REFERENCES "classe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matiere_niveaux_niveau" ADD CONSTRAINT "FK_ac166a6307dbb4c3444883bcb04" FOREIGN KEY ("matiereId") REFERENCES "matiere"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "matiere_niveaux_niveau" ADD CONSTRAINT "FK_510ff6dfa7c7fc7db89454b3def" FOREIGN KEY ("niveauId") REFERENCES "niveau"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classe_niveaux_niveau" ADD CONSTRAINT "FK_0751cfed69f5118e28b0f59cc51" FOREIGN KEY ("classeId") REFERENCES "classe"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "classe_niveaux_niveau" ADD CONSTRAINT "FK_3b539ebc24d214d2b9d475ccb01" FOREIGN KEY ("niveauId") REFERENCES "niveau"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classe_etablissements_etablissement" ADD CONSTRAINT "FK_784cc0d337f317933fcb60e8cd6" FOREIGN KEY ("classeId") REFERENCES "classe"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "classe_etablissements_etablissement" ADD CONSTRAINT "FK_088b44971f54346dcfc8d65e654" FOREIGN KEY ("etablissementId") REFERENCES "etablissement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "etudiant_parents_parent" ADD CONSTRAINT "FK_2212949f041b51e9feba7d1ef71" FOREIGN KEY ("etudiantId") REFERENCES "etudiant"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "etudiant_parents_parent" ADD CONSTRAINT "FK_5bc7232bd477fd09dfccd0fa2f9" FOREIGN KEY ("parentId") REFERENCES "parent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devoir_documents_document" ADD CONSTRAINT "FK_321263efd34b2347abc727a3db2" FOREIGN KEY ("devoirId") REFERENCES "devoir"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "devoir_documents_document" ADD CONSTRAINT "FK_e178e1719d8888ce676305b6fb3" FOREIGN KEY ("documentId") REFERENCES "document"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "devoir_documents_document" DROP CONSTRAINT "FK_e178e1719d8888ce676305b6fb3"`);
        await queryRunner.query(`ALTER TABLE "devoir_documents_document" DROP CONSTRAINT "FK_321263efd34b2347abc727a3db2"`);
        await queryRunner.query(`ALTER TABLE "etudiant_parents_parent" DROP CONSTRAINT "FK_5bc7232bd477fd09dfccd0fa2f9"`);
        await queryRunner.query(`ALTER TABLE "etudiant_parents_parent" DROP CONSTRAINT "FK_2212949f041b51e9feba7d1ef71"`);
        await queryRunner.query(`ALTER TABLE "classe_etablissements_etablissement" DROP CONSTRAINT "FK_088b44971f54346dcfc8d65e654"`);
        await queryRunner.query(`ALTER TABLE "classe_etablissements_etablissement" DROP CONSTRAINT "FK_784cc0d337f317933fcb60e8cd6"`);
        await queryRunner.query(`ALTER TABLE "classe_niveaux_niveau" DROP CONSTRAINT "FK_3b539ebc24d214d2b9d475ccb01"`);
        await queryRunner.query(`ALTER TABLE "classe_niveaux_niveau" DROP CONSTRAINT "FK_0751cfed69f5118e28b0f59cc51"`);
        await queryRunner.query(`ALTER TABLE "matiere_niveaux_niveau" DROP CONSTRAINT "FK_510ff6dfa7c7fc7db89454b3def"`);
        await queryRunner.query(`ALTER TABLE "matiere_niveaux_niveau" DROP CONSTRAINT "FK_ac166a6307dbb4c3444883bcb04"`);
        await queryRunner.query(`ALTER TABLE "matiere_classes_classe" DROP CONSTRAINT "FK_a2869b0551842a5c9451022ccf5"`);
        await queryRunner.query(`ALTER TABLE "matiere_classes_classe" DROP CONSTRAINT "FK_22a30809aa7986c75e2039415cd"`);
        await queryRunner.query(`ALTER TABLE "submission" DROP CONSTRAINT "FK_c988039646d519e39bb3e60763b"`);
        await queryRunner.query(`ALTER TABLE "submission" DROP CONSTRAINT "FK_9c4fbb41ae92b5259998ed4eb02"`);
        await queryRunner.query(`ALTER TABLE "submission" DROP CONSTRAINT "FK_229a7b4af2a0721748debbe8319"`);
        await queryRunner.query(`ALTER TABLE "devoir" DROP CONSTRAINT "FK_b03700a0002517676721f794eb7"`);
        await queryRunner.query(`ALTER TABLE "devoir" DROP CONSTRAINT "FK_5491a103593c76073a4c2cd8630"`);
        await queryRunner.query(`ALTER TABLE "devoir" DROP CONSTRAINT "FK_dd09647a10e9975c4348b6451c7"`);
        await queryRunner.query(`ALTER TABLE "devoir" DROP CONSTRAINT "FK_14a13fbb137c516489e2824e04f"`);
        await queryRunner.query(`ALTER TABLE "discipline" DROP CONSTRAINT "FK_3715bacd8203d0d4e4b84fba874"`);
        await queryRunner.query(`ALTER TABLE "facture" DROP CONSTRAINT "FK_64543711312f99b6b0d20bee443"`);
        await queryRunner.query(`ALTER TABLE "facture" DROP CONSTRAINT "FK_a570b903e0d06d8224cd9117e11"`);
        await queryRunner.query(`ALTER TABLE "paiement" DROP CONSTRAINT "FK_3ee9f6d47d1826661643362f095"`);
        await queryRunner.query(`ALTER TABLE "paiement" DROP CONSTRAINT "FK_017db846a888e629356ff387b9c"`);
        await queryRunner.query(`ALTER TABLE "frais" DROP CONSTRAINT "FK_91a9941485422fe1bdf62992360"`);
        await queryRunner.query(`ALTER TABLE "frais" DROP CONSTRAINT "FK_6c2e48ceac45e820d2c81d6ad8c"`);
        await queryRunner.query(`ALTER TABLE "frais" DROP CONSTRAINT "FK_e27c9b14dc1e3cd3b1fac93e1a4"`);
        await queryRunner.query(`ALTER TABLE "document" DROP CONSTRAINT "FK_5bda5f75563f39f9c04adb2c2e0"`);
        await queryRunner.query(`ALTER TABLE "generated_document" DROP CONSTRAINT "FK_5b8e7fe3afc5db77c8fab3562ea"`);
        await queryRunner.query(`ALTER TABLE "generated_document" DROP CONSTRAINT "FK_8a4f6342c1497befc72fcf77209"`);
        await queryRunner.query(`ALTER TABLE "generated_document" DROP CONSTRAINT "FK_24429ddfd06252b36dfcad9b64a"`);
        await queryRunner.query(`ALTER TABLE "daily_report" DROP CONSTRAINT "FK_5ac09ae78730d47cd5ff9709aca"`);
        await queryRunner.query(`ALTER TABLE "presence" DROP CONSTRAINT "FK_5875ce03aa167454398165438bc"`);
        await queryRunner.query(`ALTER TABLE "presence" DROP CONSTRAINT "FK_bd046074eae94d956a26d543596"`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" DROP CONSTRAINT "FK_fafd307a2d33552eac0d6c9b813"`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" DROP CONSTRAINT "FK_c51abc62a76489a373300d09987"`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" DROP CONSTRAINT "FK_7a966c97def9a503efc93fba589"`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" DROP CONSTRAINT "FK_3f7d27b0ea32948a1600562e8a1"`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" DROP CONSTRAINT "FK_bb3490f327d918721d50af10e80"`);
        await queryRunner.query(`ALTER TABLE "emploi_du_temp" DROP CONSTRAINT "FK_1382506f6fd3d07eb8d61f981a9"`);
        await queryRunner.query(`ALTER TABLE "salle" DROP CONSTRAINT "FK_108d792fb7c93aa0c6dd4c55954"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c86f56da7bb30c073e3cbed4e50"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_f79fcd085b54535dac75c3067b1"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_b9c580c0212198ddb97e5ea5bd9"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_cb18d5a151a72a134ae51aa0d87"`);
        await queryRunner.query(`ALTER TABLE "etudiant" DROP CONSTRAINT "FK_46cf6d4bedfa6cc798b41ff2907"`);
        await queryRunner.query(`ALTER TABLE "etudiant" DROP CONSTRAINT "FK_06fb9edb6e6692c435662451cd1"`);
        await queryRunner.query(`ALTER TABLE "etudiant" DROP CONSTRAINT "FK_e3766f31057ed43026791719c74"`);
        await queryRunner.query(`ALTER TABLE "inscription" DROP CONSTRAINT "FK_6554e7dddc36d921a306fb6752d"`);
        await queryRunner.query(`ALTER TABLE "inscription" DROP CONSTRAINT "FK_3742e0aa85aa466967d70a7f2d2"`);
        await queryRunner.query(`ALTER TABLE "inscription" DROP CONSTRAINT "FK_97bd35545695c54b5a2c325777d"`);
        await queryRunner.query(`ALTER TABLE "inscription" DROP CONSTRAINT "FK_8dd3b031b9bac17fee9a4a49cef"`);
        await queryRunner.query(`ALTER TABLE "inscription" DROP CONSTRAINT "FK_ca3fe1c599dc9cff1cbaa78cb7e"`);
        await queryRunner.query(`ALTER TABLE "semestre" DROP CONSTRAINT "FK_c06f21c4017f0f6be454c1a853a"`);
        await queryRunner.query(`ALTER TABLE "evaluation" DROP CONSTRAINT "FK_c879e3d03a063bfcc941ef8be10"`);
        await queryRunner.query(`ALTER TABLE "evaluation" DROP CONSTRAINT "FK_a635f6de622e9f36bb4098363b1"`);
        await queryRunner.query(`ALTER TABLE "evaluation" DROP CONSTRAINT "FK_00a80169171331f141b6d288332"`);
        await queryRunner.query(`ALTER TABLE "evaluation" DROP CONSTRAINT "FK_29bf8ae04788e70fece77a39fc0"`);
        await queryRunner.query(`ALTER TABLE "note" DROP CONSTRAINT "FK_9a6eb74f4efaf1c10d9511b86fd"`);
        await queryRunner.query(`ALTER TABLE "note" DROP CONSTRAINT "FK_028dab9170f200af38322b8d784"`);
        await queryRunner.query(`ALTER TABLE "sanction" DROP CONSTRAINT "FK_96aa9801da4a8adae770d60a786"`);
        await queryRunner.query(`ALTER TABLE "affectation" DROP CONSTRAINT "FK_0cab327cd4501e22d71f34adcda"`);
        await queryRunner.query(`ALTER TABLE "affectation" DROP CONSTRAINT "FK_9789642b0225bbabaabb3657729"`);
        await queryRunner.query(`ALTER TABLE "affectation" DROP CONSTRAINT "FK_acd89d309a795478b5ad80ea88f"`);
        await queryRunner.query(`ALTER TABLE "affectation" DROP CONSTRAINT "FK_65869dbaafbed6bf2a16166f751"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e178e1719d8888ce676305b6fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_321263efd34b2347abc727a3db"`);
        await queryRunner.query(`DROP TABLE "devoir_documents_document"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bc7232bd477fd09dfccd0fa2f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2212949f041b51e9feba7d1ef7"`);
        await queryRunner.query(`DROP TABLE "etudiant_parents_parent"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_088b44971f54346dcfc8d65e65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_784cc0d337f317933fcb60e8cd"`);
        await queryRunner.query(`DROP TABLE "classe_etablissements_etablissement"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b539ebc24d214d2b9d475ccb0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0751cfed69f5118e28b0f59cc5"`);
        await queryRunner.query(`DROP TABLE "classe_niveaux_niveau"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_510ff6dfa7c7fc7db89454b3de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac166a6307dbb4c3444883bcb0"`);
        await queryRunner.query(`DROP TABLE "matiere_niveaux_niveau"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2869b0551842a5c9451022ccf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22a30809aa7986c75e2039415c"`);
        await queryRunner.query(`DROP TABLE "matiere_classes_classe"`);
        await queryRunner.query(`DROP TABLE "global_setting"`);
        await queryRunner.query(`DROP TYPE "public"."global_setting_category_enum"`);
        await queryRunner.query(`DROP TABLE "submission"`);
        await queryRunner.query(`DROP TABLE "devoir"`);
        await queryRunner.query(`DROP TABLE "discipline"`);
        await queryRunner.query(`DROP TYPE "public"."discipline_category_enum"`);
        await queryRunner.query(`DROP TABLE "facture"`);
        await queryRunner.query(`DROP TABLE "paiement"`);
        await queryRunner.query(`DROP TABLE "frais"`);
        await queryRunner.query(`DROP TABLE "document"`);
        await queryRunner.query(`DROP TABLE "generated_document"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5111c7228266231d9a0b584cd"`);
        await queryRunner.query(`DROP TABLE "daily_report"`);
        await queryRunner.query(`DROP TABLE "presence"`);
        await queryRunner.query(`DROP TABLE "emploi_du_temp"`);
        await queryRunner.query(`DROP TABLE "salle"`);
        await queryRunner.query(`DROP TABLE "enseignant"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP TABLE "etudiant"`);
        await queryRunner.query(`DROP TABLE "inscription"`);
        await queryRunner.query(`DROP TABLE "annee_universitaire"`);
        await queryRunner.query(`DROP TABLE "semestre"`);
        await queryRunner.query(`DROP TABLE "evaluation"`);
        await queryRunner.query(`DROP TABLE "note"`);
        await queryRunner.query(`DROP TABLE "sanction"`);
        await queryRunner.query(`DROP TABLE "parent"`);
        await queryRunner.query(`DROP TABLE "affectation"`);
        await queryRunner.query(`DROP TABLE "etablissement"`);
        await queryRunner.query(`DROP TABLE "classe"`);
        await queryRunner.query(`DROP TABLE "niveau"`);
        await queryRunner.query(`DROP TABLE "matiere"`);
    }

}
